# Generated by Django 3.2.7 on 2021-10-11 16:19

import ckeditor.fields
import colorfield.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='descripción')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'categoria de servicio',
                'verbose_name_plural': 'categorias de servicios',
            },
        ),
        migrations.CreateModel(
            name='CommunicationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='código')),
                ('description', models.CharField(max_length=150, verbose_name='descripción')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'canal de comunicación',
                'verbose_name_plural': 'canales de comunicación',
                'db_table': 'request_communication_channel',
            },
        ),
        migrations.CreateModel(
            name='ComponentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'componente de acción formularios',
                'verbose_name_plural': 'componentes de acción formularios',
                'db_table': 'request_component_action',
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='nombre de componente')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'tipo de componente',
                'verbose_name_plural': 'tipos de componentes',
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=150, verbose_name='Fuente de datos')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
                ('related_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_related', to='request.datasource', verbose_name='Fuente de datos relacionada')),
            ],
            options={
                'verbose_name': 'fuente de datos',
                'verbose_name_plural': 'fuentes de datos',
                'db_table': 'request_data_source',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='nombre entidad')),
                ('email', models.EmailField(max_length=200, verbose_name='correo electrónico')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
                ('root_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_subordination', to='request.entity', verbose_name='entidad padre')),
            ],
            options={
                'verbose_name': 'entidad',
                'verbose_name_plural': 'entidades',
            },
        ),
        migrations.CreateModel(
            name='FooterWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='descripción')),
                ('text_html', ckeditor.fields.RichTextField(verbose_name='texto HTML')),
                ('orientation', models.CharField(choices=[('V', 'Vertical'), ('H', 'Horizontal')], max_length=1, verbose_name='orientación')),
                ('order_display', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero')], max_length=80, verbose_name='orden para mostrar')),
                ('is_active', models.BooleanField(default=False, verbose_name='activo')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'pie de pagina',
                'verbose_name_plural': 'pies de paginas',
                'db_table': 'request_footer_web',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='descripción')),
                ('letter_text', ckeditor.fields.RichTextField(verbose_name='contenido')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'Carta',
                'verbose_name_plural': 'Cartas',
            },
        ),
        migrations.CreateModel(
            name='MainSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='descripción')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'sección principal',
                'verbose_name_plural': 'secciones principales',
                'db_table': 'request_main_section',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('priority_percentage', models.FloatField(default=0.0, verbose_name='porcentaje de prioridad')),
                ('color_priority', colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='Color de prioridad')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'prioridad de servicio',
                'verbose_name_plural': 'prioridades de servicios',
                'db_table': 'request_priority',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='descripción')),
                ('web_indicator', models.BooleanField(default=False, verbose_name='indicador web')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
                ('category_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.categoryservice', verbose_name='categoria de servicio')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.entity', verbose_name='entidad prestadora')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='ServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_filter_api', models.CharField(max_length=2000, null=True, verbose_name='filtro poblacional API')),
                ('start_date', models.DateField(null=True, verbose_name='fecha de inicio')),
                ('end_date', models.DateField(null=True, verbose_name='fecha fin')),
                ('delivery_days', models.IntegerField(default=False, null=True, verbose_name='dias de entrega')),
                ('bussiness_days', models.BooleanField(default=False, null=True, verbose_name='dias laborales')),
                ('working_hours', models.BooleanField(default=False, null=True, verbose_name='horas laborales')),
                ('is_active', models.BooleanField(default=False, null=True, verbose_name='activo')),
                ('is_payment', models.BooleanField(default=False, null=True, verbose_name='Requiere pago')),
                ('generation_process', models.CharField(choices=[(1, 'Automático'), (2, 'Semi-automático'), (3, 'Manual')], max_length=2, null=True, verbose_name='Procesamiento')),
                ('cost_of_service_currency', djmoney.models.fields.CurrencyField(choices=[('XUA', 'ADB Unit of Account'), ('AFN', 'Afghan Afghani'), ('AFA', 'Afghan Afghani (1927–2002)'), ('ALL', 'Albanian Lek'), ('ALK', 'Albanian Lek (1946–1965)'), ('DZD', 'Algerian Dinar'), ('ADP', 'Andorran Peseta'), ('AOA', 'Angolan Kwanza'), ('AOK', 'Angolan Kwanza (1977–1991)'), ('AON', 'Angolan New Kwanza (1990–2000)'), ('AOR', 'Angolan Readjusted Kwanza (1995–1999)'), ('ARA', 'Argentine Austral'), ('ARS', 'Argentine Peso'), ('ARM', 'Argentine Peso (1881–1970)'), ('ARP', 'Argentine Peso (1983–1985)'), ('ARL', 'Argentine Peso Ley (1970–1983)'), ('AMD', 'Armenian Dram'), ('AWG', 'Aruban Florin'), ('AUD', 'Australian Dollar'), ('ATS', 'Austrian Schilling'), ('AZN', 'Azerbaijani Manat'), ('AZM', 'Azerbaijani Manat (1993–2006)'), ('BSD', 'Bahamian Dollar'), ('BHD', 'Bahraini Dinar'), ('BDT', 'Bangladeshi Taka'), ('BBD', 'Barbadian Dollar'), ('BYN', 'Belarusian Ruble'), ('BYB', 'Belarusian Ruble (1994–1999)'), ('BYR', 'Belarusian Ruble (2000–2016)'), ('BEF', 'Belgian Franc'), ('BEC', 'Belgian Franc (convertible)'), ('BEL', 'Belgian Franc (financial)'), ('BZD', 'Belize Dollar'), ('BMD', 'Bermudan Dollar'), ('BTN', 'Bhutanese Ngultrum'), ('BOB', 'Bolivian Boliviano'), ('BOL', 'Bolivian Boliviano (1863–1963)'), ('BOV', 'Bolivian Mvdol'), ('BOP', 'Bolivian Peso'), ('BAM', 'Bosnia-Herzegovina Convertible Mark'), ('BAD', 'Bosnia-Herzegovina Dinar (1992–1994)'), ('BAN', 'Bosnia-Herzegovina New Dinar (1994–1997)'), ('BWP', 'Botswanan Pula'), ('BRC', 'Brazilian Cruzado (1986–1989)'), ('BRZ', 'Brazilian Cruzeiro (1942–1967)'), ('BRE', 'Brazilian Cruzeiro (1990–1993)'), ('BRR', 'Brazilian Cruzeiro (1993–1994)'), ('BRN', 'Brazilian New Cruzado (1989–1990)'), ('BRB', 'Brazilian New Cruzeiro (1967–1986)'), ('BRL', 'Brazilian Real'), ('GBP', 'British Pound'), ('BND', 'Brunei Dollar'), ('BGL', 'Bulgarian Hard Lev'), ('BGN', 'Bulgarian Lev'), ('BGO', 'Bulgarian Lev (1879–1952)'), ('BGM', 'Bulgarian Socialist Lev'), ('BUK', 'Burmese Kyat'), ('BIF', 'Burundian Franc'), ('XPF', 'CFP Franc'), ('KHR', 'Cambodian Riel'), ('CAD', 'Canadian Dollar'), ('CVE', 'Cape Verdean Escudo'), ('KYD', 'Cayman Islands Dollar'), ('XAF', 'Central African CFA Franc'), ('CLE', 'Chilean Escudo'), ('CLP', 'Chilean Peso'), ('CLF', 'Chilean Unit of Account (UF)'), ('CNX', 'Chinese People’s Bank Dollar'), ('CNY', 'Chinese Yuan'), ('CNH', 'Chinese Yuan (offshore)'), ('COP', 'Colombian Peso'), ('COU', 'Colombian Real Value Unit'), ('KMF', 'Comorian Franc'), ('CDF', 'Congolese Franc'), ('CRC', 'Costa Rican Colón'), ('HRD', 'Croatian Dinar'), ('HRK', 'Croatian Kuna'), ('CUC', 'Cuban Convertible Peso'), ('CUP', 'Cuban Peso'), ('CYP', 'Cypriot Pound'), ('CZK', 'Czech Koruna'), ('CSK', 'Czechoslovak Hard Koruna'), ('DKK', 'Danish Krone'), ('DJF', 'Djiboutian Franc'), ('DOP', 'Dominican Peso'), ('NLG', 'Dutch Guilder'), ('XCD', 'East Caribbean Dollar'), ('DDM', 'East German Mark'), ('ECS', 'Ecuadorian Sucre'), ('ECV', 'Ecuadorian Unit of Constant Value'), ('EGP', 'Egyptian Pound'), ('GQE', 'Equatorial Guinean Ekwele'), ('ERN', 'Eritrean Nakfa'), ('EEK', 'Estonian Kroon'), ('ETB', 'Ethiopian Birr'), ('EUR', 'Euro'), ('XBA', 'European Composite Unit'), ('XEU', 'European Currency Unit'), ('XBB', 'European Monetary Unit'), ('XBC', 'European Unit of Account (XBC)'), ('XBD', 'European Unit of Account (XBD)'), ('FKP', 'Falkland Islands Pound'), ('FJD', 'Fijian Dollar'), ('FIM', 'Finnish Markka'), ('FRF', 'French Franc'), ('XFO', 'French Gold Franc'), ('XFU', 'French UIC-Franc'), ('GMD', 'Gambian Dalasi'), ('GEK', 'Georgian Kupon Larit'), ('GEL', 'Georgian Lari'), ('DEM', 'German Mark'), ('GHS', 'Ghanaian Cedi'), ('GHC', 'Ghanaian Cedi (1979–2007)'), ('GIP', 'Gibraltar Pound'), ('XAU', 'Gold'), ('GRD', 'Greek Drachma'), ('GTQ', 'Guatemalan Quetzal'), ('GWP', 'Guinea-Bissau Peso'), ('GNF', 'Guinean Franc'), ('GNS', 'Guinean Syli'), ('GYD', 'Guyanaese Dollar'), ('HTG', 'Haitian Gourde'), ('HNL', 'Honduran Lempira'), ('HKD', 'Hong Kong Dollar'), ('HUF', 'Hungarian Forint'), ('IMP', 'IMP'), ('ISK', 'Icelandic Króna'), ('ISJ', 'Icelandic Króna (1918–1981)'), ('INR', 'Indian Rupee'), ('IDR', 'Indonesian Rupiah'), ('IRR', 'Iranian Rial'), ('IQD', 'Iraqi Dinar'), ('IEP', 'Irish Pound'), ('ILS', 'Israeli New Shekel'), ('ILP', 'Israeli Pound'), ('ILR', 'Israeli Shekel (1980–1985)'), ('ITL', 'Italian Lira'), ('JMD', 'Jamaican Dollar'), ('JPY', 'Japanese Yen'), ('JOD', 'Jordanian Dinar'), ('KZT', 'Kazakhstani Tenge'), ('KES', 'Kenyan Shilling'), ('KWD', 'Kuwaiti Dinar'), ('KGS', 'Kyrgystani Som'), ('LAK', 'Laotian Kip'), ('LVL', 'Latvian Lats'), ('LVR', 'Latvian Ruble'), ('LBP', 'Lebanese Pound'), ('LSL', 'Lesotho Loti'), ('LRD', 'Liberian Dollar'), ('LYD', 'Libyan Dinar'), ('LTL', 'Lithuanian Litas'), ('LTT', 'Lithuanian Talonas'), ('LUL', 'Luxembourg Financial Franc'), ('LUC', 'Luxembourgian Convertible Franc'), ('LUF', 'Luxembourgian Franc'), ('MOP', 'Macanese Pataca'), ('MKD', 'Macedonian Denar'), ('MKN', 'Macedonian Denar (1992–1993)'), ('MGA', 'Malagasy Ariary'), ('MGF', 'Malagasy Franc'), ('MWK', 'Malawian Kwacha'), ('MYR', 'Malaysian Ringgit'), ('MVR', 'Maldivian Rufiyaa'), ('MVP', 'Maldivian Rupee (1947–1981)'), ('MLF', 'Malian Franc'), ('MTL', 'Maltese Lira'), ('MTP', 'Maltese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('MRO', 'Mauritanian Ouguiya (1973–2017)'), ('MUR', 'Mauritian Rupee'), ('MXV', 'Mexican Investment Unit'), ('MXN', 'Mexican Peso'), ('MXP', 'Mexican Silver Peso (1861–1992)'), ('MDC', 'Moldovan Cupon'), ('MDL', 'Moldovan Leu'), ('MCF', 'Monegasque Franc'), ('MNT', 'Mongolian Tugrik'), ('MAD', 'Moroccan Dirham'), ('MAF', 'Moroccan Franc'), ('MZE', 'Mozambican Escudo'), ('MZN', 'Mozambican Metical'), ('MZM', 'Mozambican Metical (1980–2006)'), ('MMK', 'Myanmar Kyat'), ('NAD', 'Namibian Dollar'), ('NPR', 'Nepalese Rupee'), ('ANG', 'Netherlands Antillean Guilder'), ('TWD', 'New Taiwan Dollar'), ('NZD', 'New Zealand Dollar'), ('NIO', 'Nicaraguan Córdoba'), ('NIC', 'Nicaraguan Córdoba (1988–1991)'), ('NGN', 'Nigerian Naira'), ('KPW', 'North Korean Won'), ('NOK', 'Norwegian Krone'), ('OMR', 'Omani Rial'), ('PKR', 'Pakistani Rupee'), ('XPD', 'Palladium'), ('PAB', 'Panamanian Balboa'), ('PGK', 'Papua New Guinean Kina'), ('PYG', 'Paraguayan Guarani'), ('PEI', 'Peruvian Inti'), ('PEN', 'Peruvian Sol'), ('PES', 'Peruvian Sol (1863–1965)'), ('PHP', 'Philippine Piso'), ('XPT', 'Platinum'), ('PLN', 'Polish Zloty'), ('PLZ', 'Polish Zloty (1950–1995)'), ('PTE', 'Portuguese Escudo'), ('GWE', 'Portuguese Guinea Escudo'), ('QAR', 'Qatari Rial'), ('XRE', 'RINET Funds'), ('RHD', 'Rhodesian Dollar'), ('RON', 'Romanian Leu'), ('ROL', 'Romanian Leu (1952–2006)'), ('RUB', 'Russian Ruble'), ('RUR', 'Russian Ruble (1991–1998)'), ('RWF', 'Rwandan Franc'), ('SVC', 'Salvadoran Colón'), ('WST', 'Samoan Tala'), ('SAR', 'Saudi Riyal'), ('RSD', 'Serbian Dinar'), ('CSD', 'Serbian Dinar (2002–2006)'), ('SCR', 'Seychellois Rupee'), ('SLL', 'Sierra Leonean Leone'), ('XAG', 'Silver'), ('SGD', 'Singapore Dollar'), ('SKK', 'Slovak Koruna'), ('SIT', 'Slovenian Tolar'), ('SBD', 'Solomon Islands Dollar'), ('SOS', 'Somali Shilling'), ('ZAR', 'South African Rand'), ('ZAL', 'South African Rand (financial)'), ('KRH', 'South Korean Hwan (1953–1962)'), ('KRW', 'South Korean Won'), ('KRO', 'South Korean Won (1945–1953)'), ('SSP', 'South Sudanese Pound'), ('SUR', 'Soviet Rouble'), ('ESP', 'Spanish Peseta'), ('ESA', 'Spanish Peseta (A account)'), ('ESB', 'Spanish Peseta (convertible account)'), ('XDR', 'Special Drawing Rights'), ('LKR', 'Sri Lankan Rupee'), ('SHP', 'St. Helena Pound'), ('XSU', 'Sucre'), ('SDD', 'Sudanese Dinar (1992–2007)'), ('SDG', 'Sudanese Pound'), ('SDP', 'Sudanese Pound (1957–1998)'), ('SRD', 'Surinamese Dollar'), ('SRG', 'Surinamese Guilder'), ('SZL', 'Swazi Lilangeni'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('SYP', 'Syrian Pound'), ('STN', 'São Tomé & Príncipe Dobra'), ('STD', 'São Tomé & Príncipe Dobra (1977–2017)'), ('TVD', 'TVD'), ('TJR', 'Tajikistani Ruble'), ('TJS', 'Tajikistani Somoni'), ('TZS', 'Tanzanian Shilling'), ('XTS', 'Testing Currency Code'), ('THB', 'Thai Baht'), ('XXX', 'The codes assigned for transactions where no currency is involved'), ('TPE', 'Timorese Escudo'), ('TOP', 'Tongan Paʻanga'), ('TTD', 'Trinidad & Tobago Dollar'), ('TND', 'Tunisian Dinar'), ('TRY', 'Turkish Lira'), ('TRL', 'Turkish Lira (1922–2005)'), ('TMT', 'Turkmenistani Manat'), ('TMM', 'Turkmenistani Manat (1993–2009)'), ('USD', 'US Dollar'), ('USN', 'US Dollar (Next day)'), ('USS', 'US Dollar (Same day)'), ('UGX', 'Ugandan Shilling'), ('UGS', 'Ugandan Shilling (1966–1987)'), ('UAH', 'Ukrainian Hryvnia'), ('UAK', 'Ukrainian Karbovanets'), ('AED', 'United Arab Emirates Dirham'), ('UYW', 'Uruguayan Nominal Wage Index Unit'), ('UYU', 'Uruguayan Peso'), ('UYP', 'Uruguayan Peso (1975–1993)'), ('UYI', 'Uruguayan Peso (Indexed Units)'), ('UZS', 'Uzbekistani Som'), ('VUV', 'Vanuatu Vatu'), ('VES', 'Venezuelan Bolívar'), ('VEB', 'Venezuelan Bolívar (1871–2008)'), ('VEF', 'Venezuelan Bolívar (2008–2018)'), ('VND', 'Vietnamese Dong'), ('VNN', 'Vietnamese Dong (1978–1985)'), ('CHE', 'WIR Euro'), ('CHW', 'WIR Franc'), ('XOF', 'West African CFA Franc'), ('YDD', 'Yemeni Dinar'), ('YER', 'Yemeni Rial'), ('YUN', 'Yugoslavian Convertible Dinar (1990–1992)'), ('YUD', 'Yugoslavian Hard Dinar (1966–1990)'), ('YUM', 'Yugoslavian New Dinar (1994–2002)'), ('YUR', 'Yugoslavian Reformed Dinar (1992–1993)'), ('ZWN', 'ZWN'), ('ZRN', 'Zairean New Zaire (1993–1998)'), ('ZRZ', 'Zairean Zaire (1971–1993)'), ('ZMW', 'Zambian Kwacha'), ('ZMK', 'Zambian Kwacha (1968–2012)'), ('ZWD', 'Zimbabwean Dollar (1980–2008)'), ('ZWR', 'Zimbabwean Dollar (2008)'), ('ZWL', 'Zimbabwean Dollar (2009)')], default='COP', editable=False, max_length=3)),
                ('cost_of_service', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='COP', max_digits=14, null=True, verbose_name='Costo del servicio')),
                ('days_validity_document', models.IntegerField(default=0, verbose_name='dias de vigencia documento')),
                ('digital_document', models.BooleanField(default=False, null=True, verbose_name='documento digital')),
                ('physical_document', models.BooleanField(default=False, null=True, verbose_name='dumento fisico')),
                ('comments', ckeditor.fields.RichTextField(verbose_name='comentarios del servicio')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'regla del servicio',
                'verbose_name_plural': 'reglas del servicio',
                'db_table': 'request_service_configuration',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='código de estado')),
                ('description', models.CharField(max_length=150, verbose_name='descripción')),
                ('completion_status', models.BooleanField(verbose_name='estado de terminación')),
                ('visible_state', models.BooleanField(verbose_name='estado visible')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'estado de solicitud',
                'verbose_name_plural': 'estados de solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='descripción')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
                ('key_config', models.CharField(blank=True, max_length=10, null=True, verbose_name='key config')),
            ],
            options={
                'verbose_name': 'subsección',
                'verbose_name_plural': 'subsecciones',
                'db_table': 'request_subsection',
            },
        ),
        migrations.CreateModel(
            name='subsectionServiceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(null=True, verbose_name='activo')),
                ('order_display', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto')], max_length=80, verbose_name='orden para mostrar')),
                ('rule_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules_service_main_form_subsection', to='request.serviceconfiguration', verbose_name='Regla de servicio')),
                ('section_main_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_form', to='request.mainsection', verbose_name='grupo principal del formulario')),
                ('subsection_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsection_form', to='request.subsection', verbose_name='subsección formulario')),
            ],
            options={
                'verbose_name': 'componente y seccion form',
                'verbose_name_plural': 'componentes y secciones form',
                'db_table': 'request_section_component',
            },
        ),
        migrations.CreateModel(
            name='ServiceConfigurationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_start', models.BooleanField(verbose_name='Estado de inicio')),
                ('status_finished', models.BooleanField(verbose_name='estado de fin')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
                ('assign_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuario asignado')),
                ('rule_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.serviceconfiguration', verbose_name='Servicio')),
                ('status_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.status', verbose_name='Estado de solicitud')),
            ],
            options={
                'verbose_name': 'estado relacionado a solicitud',
                'verbose_name_plural': 'estados relacionados a solicitudes',
                'db_table': 'request_status_related_request',
            },
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='related_status',
            field=models.ManyToManyField(through='request.ServiceConfigurationStatus', to='request.Status'),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='role de acceso'),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.service', verbose_name='servicio'),
        ),
        migrations.CreateModel(
            name='MainFormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(null=True, verbose_name='activo')),
                ('order_display', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto')], max_length=80, verbose_name='orden para mostrar')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
                ('main_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_section_form', to='request.mainsection', verbose_name='Sección principal formulario')),
                ('rule_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules_service_main_form_section', to='request.serviceconfiguration', verbose_name='Regla de servicio')),
            ],
            options={
                'verbose_name': 'seccion principal y componentes form',
                'verbose_name_plural': 'secciones principales y componentes form',
                'db_table': 'request_main_form_section',
            },
        ),
        migrations.CreateModel(
            name='LetterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripción')),
                ('order_display', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto')], max_length=80, verbose_name='orden para mostrar')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.letter', verbose_name='carta')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.service', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'asociación de servicio y carta',
                'verbose_name_plural': 'asociar servicios y cartas',
            },
        ),
        migrations.CreateModel(
            name='DataSourceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_data', models.CharField(max_length=4, verbose_name='código datos de la fuente')),
                ('value_data', models.CharField(max_length=100, verbose_name='valor datos de la fuente')),
                ('data_related', models.CharField(max_length=4, null=True, verbose_name='dato de fuente relacionada')),
                ('source_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataSourceValue', to='request.datasource', verbose_name='fuente de datos')),
            ],
            options={
                'verbose_name': 'Valor de fuente de datos',
                'verbose_name_plural': 'valores de fuentes de datos',
                'db_table': 'request_data_source_value',
            },
        ),
        migrations.CreateModel(
            name='ConfigVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='código')),
                ('description', models.CharField(max_length=150, verbose_name='descripción')),
                ('value', models.CharField(max_length=20, verbose_name='valor')),
                ('sequence', models.IntegerField(default=1, verbose_name='secuencia')),
                ('system_required', models.BooleanField(default=False, verbose_name='requerido por sistema')),
                ('group_variable', models.CharField(max_length=10, verbose_name='grupo de variables')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'variable de configuración',
                'verbose_name_plural': 'variables de configuración',
                'db_table': 'request_config_variable',
                'unique_together': {('group_variable', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ComponentSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='etiqueta del componente')),
                ('required', models.BooleanField(null=True, verbose_name='requerido')),
                ('source_api', models.CharField(max_length=2000, null=True, verbose_name='fuente de datos API')),
                ('key_head', models.CharField(blank='', max_length=10, verbose_name='key head')),
                ('order_display', models.IntegerField(null=True, verbose_name='orden despliegue')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.componenttype', verbose_name='componente')),
                ('rule_subsection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.subsectionserviceform', verbose_name='Subsección de servicio')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='request.datasource', verbose_name='fuente de datos')),
            ],
            options={
                'verbose_name': 'subsección y componente',
                'verbose_name_plural': 'subsecciones y componentes',
                'db_table': 'request_component_subsection',
            },
        ),
        migrations.CreateModel(
            name='ComponentMainForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='etiqueta del componente')),
                ('required', models.BooleanField(null=True, verbose_name='requerido')),
                ('source_api', models.CharField(max_length=2000, null=True, verbose_name='fuente de datos API')),
                ('key_head', models.CharField(blank='', max_length=10, verbose_name='key head')),
                ('order_display', models.IntegerField(null=True, verbose_name='orden despliegue')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.componenttype', verbose_name='componente')),
                ('rule_main_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.mainformsection', verbose_name='Subsección de servicio')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='request.datasource', verbose_name='fuente de datos')),
            ],
            options={
                'verbose_name': 'seccion principal y componente',
                'verbose_name_plural': 'secciones principales y componentes',
                'db_table': 'request_section_main_component',
            },
        ),
        migrations.CreateModel(
            name='componentActionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_component_action_id', models.ForeignKey(blank='', on_delete=django.db.models.deletion.PROTECT, to='request.componentaction', verbose_name='regla de componente de acción')),
            ],
        ),
        migrations.AddField(
            model_name='componentaction',
            name='service_component_group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='request.mainsection', verbose_name='grupo de componentes'),
        ),
        migrations.AddField(
            model_name='componentaction',
            name='service_component_section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='request.subsection', verbose_name='seccion de formularios'),
        ),
        migrations.AddField(
            model_name='componentaction',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.serviceconfiguration', verbose_name='Servicio'),
        ),
    ]
