# Generated by Django 3.2.7 on 2021-10-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentmainform',
            name='key_head',
            field=models.CharField(blank='', choices=[], max_length=10, verbose_name='key head'),
        ),
        migrations.AlterField(
            model_name='componentsubsection',
            name='key_head',
            field=models.CharField(blank='', choices=[], max_length=10, verbose_name='key head'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='key_config',
            field=models.CharField(blank=True, choices=[], max_length=10, null=True, verbose_name='key config'),
        ),
    ]
