# Generated by Django 3.2.7 on 2021-09-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryservice',
            old_name='createt_at',
            new_name='created_at',
        ),
    ]
