# Generated by Django 3.2.7 on 2021-10-01 11:47

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_rename_createt_at_categoryservice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='categoryservice',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoryservice',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modicación'),
        ),
        migrations.AlterField(
            model_name='categoryservice',
            name='user_mod',
            field=models.CharField(blank=True, default=django.contrib.auth.models.User, max_length=50, verbose_name='Modificado por'),
        ),
    ]
