# Generated by Django 3.2.7 on 2021-10-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_datasourcevalue_data_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='population_filter_api',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='filtro poblacional API'),
        ),
    ]
