# Generated by Django 3.2.7 on 2021-10-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20211001_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryservice',
            options={'verbose_name': 'categoria de servicio', 'verbose_name_plural': 'categorias de servicios'},
        ),
        migrations.RemoveField(
            model_name='categoryservice',
            name='user_mod',
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='modificado por'),
        ),
        migrations.AlterField(
            model_name='categoryservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='categoryservice',
            name='description',
            field=models.CharField(max_length=100, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='categoryservice',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de modicación'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='descripción')),
                ('web_indicator', models.BooleanField(default=False, verbose_name='indicador web')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
                ('category_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.categoryservice')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
    ]
