# Generated by Django 3.2.7 on 2021-10-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_serviceconfiguration_population_filter_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='generation_process',
            field=models.CharField(choices=[('1', 'Automático'), ('2', 'Semi-automático'), ('3', 'Manual')], max_length=2, null=True, verbose_name='Procesamiento'),
        ),
        migrations.AlterField(
            model_name='subsectionserviceform',
            name='subsection_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsection_form', to='request.subsection', unique=True, verbose_name='subsección formulario'),
        ),
    ]
