# Generated by Django 3.2.7 on 2021-10-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20211001_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letterservice',
            options={'verbose_name': 'asociación de servicio y carta', 'verbose_name_plural': 'asociar servicios y cartas'},
        ),
        migrations.AddField(
            model_name='letterservice',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='letterservice',
            name='order_display',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='orden para mostrar'),
        ),
    ]
