# Generated by Django 3.2.7 on 2021-10-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_alter_mainformsection_main_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsectionserviceform',
            name='subsection_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsection_form', to='request.subsection', verbose_name='subsección formulario'),
        ),
        migrations.AlterUniqueTogether(
            name='subsectionserviceform',
            unique_together={('subsection_service', 'section_main_form')},
        ),
    ]
