# Generated by Django 3.2.7 on 2021-10-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_auto_20211011_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentsubsection',
            name='source_api',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='fuente de datos API'),
        ),
    ]
