# Generated by Django 3.2.7 on 2021-10-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_auto_20211001_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterservice',
            name='order_display',
            field=models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto')], default='', max_length=80, verbose_name='orden para mostrar'),
        ),
    ]
