# Generated by Django 3.2.7 on 2021-10-13 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_alter_componentsubsection_source_api'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentmainform',
            old_name='label',
            new_name='description',
        ),
        migrations.AddField(
            model_name='componentmainform',
            name='actionable_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_actionable_component', to='request.componentmainform', verbose_name='componente accionable'),
        ),
        migrations.AlterField(
            model_name='componentsubsection',
            name='key_head',
            field=models.CharField(blank=True, choices=[], max_length=10, verbose_name='key head'),
        ),
        migrations.AlterUniqueTogether(
            name='componentaction',
            unique_together={('service_id', 'service_component_group_id', 'service_component_section_id')},
        ),
    ]
