# Generated by Django 3.2.7 on 2021-10-13 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_auto_20211012_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentsubsection',
            old_name='label',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='componentmainform',
            name='actionable_component',
        ),
        migrations.AddField(
            model_name='componentsubsection',
            name='actionable_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_actionable_component', to='request.componentsubsection', verbose_name='componente accionable'),
        ),
    ]
