# Generated by Django 3.2.7 on 2021-10-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_componenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='nombre entidad')),
                ('email', models.EmailField(max_length=200, verbose_name='correo electrónico')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
                ('root_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_subordination', to='request.entity', verbose_name='entidad padre')),
            ],
            options={
                'verbose_name': 'entidad',
                'verbose_name_plural': 'entidades',
            },
        ),
    ]
