# Generated by Django 3.2.7 on 2021-10-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_auto_20211012_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentsubsection',
            name='actionable_component',
        ),
    ]
