# Generated by Django 3.2.7 on 2021-10-01 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='root_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_subordination', to='request.entity', verbose_name='entidad padre'),
        ),
    ]
