# Generated by Django 3.2.7 on 2021-10-01 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_alter_entity_root_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.entity', verbose_name='entidad prestadora'),
        ),
    ]
