# Generated by Django 3.2.7 on 2021-10-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0012_actionablecomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionablecomponent',
            name='component_action_receptor',
            field=models.CharField(blank=True, choices=[(1, 'Cedula de ciudadania'), (2, 'Ciudad de Residencia'), (3, 'XXXX'), (4, 'SSSSS')], max_length=10, verbose_name='key head'),
        ),
        migrations.AlterField(
            model_name='actionablecomponent',
            name='component_action_emisor',
            field=models.CharField(blank=True, choices=[(1, 'Cedula de ciudadania'), (2, 'Ciudad de Residencia'), (3, 'XXXX'), (4, 'SSSSS')], max_length=10, verbose_name='key head'),
        ),
    ]
