# Generated by Django 3.2.7 on 2021-10-02 01:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0012_service_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='descripción')),
                ('text_html', ckeditor.fields.RichTextField(verbose_name='texto HTML')),
                ('orientation', models.CharField(choices=[('V', 'Vertical'), ('H', 'Horizontal')], max_length=1, verbose_name='orientación')),
                ('order_display', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero')], max_length=80, verbose_name='orden para mostrar')),
                ('is_active', models.BooleanField(default=False, verbose_name='activo')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'Pie de pagina',
                'verbose_name_plural': 'Pies de paginas',
                'db_table': 'request_footer_web',
            },
        ),
        migrations.AlterField(
            model_name='letterservice',
            name='order_display',
            field=models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto')], max_length=80, verbose_name='orden para mostrar'),
        ),
    ]
