# Generated by Django 3.2.7 on 2021-10-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_auto_20211001_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='descripción')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'sección principal formulario',
                'verbose_name_plural': 'secciones principales de formularios',
                'db_table': 'request_main_section',
            },
        ),
        migrations.AlterModelOptions(
            name='footerweb',
            options={'verbose_name': 'pie de pagina', 'verbose_name_plural': 'pies de paginas'},
        ),
    ]
