# Generated by Django 3.2.7 on 2021-10-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0014_auto_20211001_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='descripción')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'subsección',
                'verbose_name_plural': 'subsecciones',
                'db_table': 'request_subsection',
            },
        ),
        migrations.AlterModelOptions(
            name='mainsection',
            options={'verbose_name': 'sección principal', 'verbose_name_plural': 'secciones principales'},
        ),
    ]
