# Generated by Django 3.2.7 on 2021-10-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_auto_20211001_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_short', models.CharField(max_length=10, verbose_name='alfanumerico')),
                ('description', models.CharField(max_length=150, verbose_name='descripción')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'Fuente de datos',
                'verbose_name_plural': 'Fuentes de datos',
                'db_table': 'request_data_source',
            },
        ),
    ]
