# Generated by Django 3.2.7 on 2021-10-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_auto_20211013_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionablecomponent',
            name='rule_component_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.componentaction', verbose_name='subsección de servicio'),
        ),
    ]
