# Generated by Django 3.2.7 on 2021-10-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_alter_actionablecomponent_rule_component_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionablecomponent',
            name='section_action_receptor',
            field=models.IntegerField(blank=True, choices=[(1, 'Cedula de ciudadania'), (2, 'Ciudad de Residencia'), (3, 'XXXX'), (4, 'SSSSS'), (5, 'Cedula de ciudadanía'), (6, 'Programa académico'), (7, 'Periodo académico'), (8, 'Programas Académios'), (9, 'Prueba Componente')], default=False, null=True, verbose_name='sección receptor'),
        ),
    ]
