# Generated by Django 3.2.7 on 2021-10-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_datasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='código')),
                ('description', models.CharField(max_length=150, verbose_name='descripción')),
                ('value', models.CharField(max_length=20, verbose_name='valor')),
                ('system_riquired', models.BooleanField(default=False, verbose_name='requerido por sistema')),
                ('group_variable', models.CharField(max_length=10, verbose_name='grupo de variables')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'variable de configuración',
                'verbose_name_plural': 'variables de configuración',
                'db_table': 'request_config_variable',
            },
        ),
        migrations.AlterModelOptions(
            name='datasource',
            options={'verbose_name': 'fuente de datos', 'verbose_name_plural': 'fuentes de datos'},
        ),
    ]
