# Generated by Django 3.2.7 on 2021-10-14 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_actionablecomponent_section_action_receptor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subsectionserviceform',
            unique_together={('rule_service', 'subsection_service', 'section_main_form')},
        ),
    ]
