# Generated by Django 3.2.7 on 2021-10-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_auto_20211002_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configvariable',
            old_name='system_riquired',
            new_name='system_required',
        ),
    ]
