# Generated by Django 3.2.7 on 2021-10-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_rename_system_riquired_configvariable_system_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='configvariable',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='secuencia'),
        ),
    ]
