# Generated by Django 3.2.7 on 2021-10-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_alter_subsectionserviceform_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentactiondetail',
            name='rule_component_action_id',
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='is_form_active',
            field=models.BooleanField(default=False, null=True, verbose_name='formulario activo'),
        ),
        migrations.DeleteModel(
            name='ActionableComponent',
        ),
        migrations.DeleteModel(
            name='componentActionDetail',
        ),
    ]
