# Generated by Django 3.2.7 on 2021-10-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_alter_configvariable_sequence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configvariable',
            unique_together={('group_variable', 'code')},
        ),
    ]
