# Generated by Django 3.2.7 on 2021-10-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0021_alter_configvariable_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='código')),
                ('description', models.CharField(max_length=150, verbose_name='descripción')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'canal de comunicación',
                'verbose_name_plural': 'canales de comunicación',
                'db_table': 'request_communication_channel',
            },
        ),
    ]
