# Generated by Django 3.2.7 on 2021-10-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0022_auto_20211014_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='digital_document',
            field=models.BooleanField(default=False, verbose_name='documento digital'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='physical_document',
            field=models.BooleanField(default=False, verbose_name='dumento fisico'),
        ),
    ]
