# Generated by Django 3.2.7 on 2021-10-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0024_auto_20211014_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestheader',
            options={'verbose_name': 'encabezado de la solicitud', 'verbose_name_plural': 'encabezados de las solicitudes'},
        ),
        migrations.AlterModelTable(
            name='requestheader',
            table='request_header',
        ),
        migrations.CreateModel(
            name='RequestBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_code', models.CharField(max_length=10, verbose_name='código de pregunta')),
                ('data_desc', models.CharField(max_length=255, verbose_name='selección de respuesta')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
                ('component_service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.componentsubsection', verbose_name='componente de formulario')),
                ('header_request_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.requestheader', verbose_name='codigo solicitud')),
            ],
            options={
                'verbose_name': 'cuerpo de la solicitud',
                'verbose_name_plural': 'cuerpo de las solicitudes',
                'db_table': 'request_body',
            },
        ),
    ]
