# Generated by Django 3.2.7 on 2021-10-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0024_auto_20211003_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='desc_short',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='description',
        ),
        migrations.AddField(
            model_name='datasource',
            name='related_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_related', to='request.datasource', verbose_name='Fuente de datos relacionada'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='source',
            field=models.CharField(default='', max_length=150, verbose_name='Fuente de datos'),
        ),
    ]
