# Generated by Django 3.2.7 on 2021-10-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0025_auto_20211003_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source',
            field=models.CharField(max_length=150, verbose_name='Fuente de datos'),
        ),
    ]
