# Generated by Django 3.2.7 on 2021-10-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0026_requesthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='header_request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='request.requestheader', verbose_name='codigo solicitud'),
        ),
    ]
