# Generated by Django 3.2.7 on 2021-10-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0026_alter_datasource_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_data', models.CharField(max_length=4, verbose_name='código datos de la fuente')),
                ('value_data', models.CharField(max_length=100, verbose_name='valor datos de la fuente')),
                ('data_related', models.CharField(max_length=4, verbose_name='dato de fuente relacionada')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
                ('source_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.datasource', verbose_name='fuente de datos')),
            ],
            options={
                'verbose_name': 'Valor de fuente de datos',
                'verbose_name_plural': 'valores de fuentes de datos',
                'db_table': 'request_data_soruce_value',
            },
        ),
    ]
