# Generated by Django 3.2.7 on 2021-10-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0027_requesthistory_header_request_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestheader',
            options={'verbose_name': 'gestión de la solicitud', 'verbose_name_plural': 'gestión de las solicitudes'},
        ),
        migrations.AlterField(
            model_name='subsectionserviceform',
            name='section_main_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_form', to='request.mainformsection', verbose_name='grupo principal del formulario'),
        ),
    ]
