# Generated by Django 3.2.7 on 2021-10-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0027_datasourcevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcevalue',
            name='source_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataSourceValue', to='request.datasource', verbose_name='fuente de datos'),
        ),
        migrations.AlterModelTable(
            name='datasourcevalue',
            table='request_data_source_value',
        ),
    ]
