# Generated by Django 3.2.7 on 2021-10-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0028_auto_20211003_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourcevalue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='datasourcevalue',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='datasourcevalue',
            name='user_id',
        ),
    ]
