# Generated by Django 3.2.7 on 2021-10-14 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0028_auto_20211014_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsectionserviceform',
            name='section_main_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_form', to='request.mainsection', verbose_name='grupo principal del formulario'),
        ),
    ]
