# Generated by Django 3.2.7 on 2021-10-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('request', '0030_auto_20211003_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='bussiness_days',
            field=models.BooleanField(null=True, verbose_name='dias laborales'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='delivery_days',
            field=models.IntegerField(max_length=2, null=True, verbose_name='dias de entrega'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='end_date',
            field=models.DateField(null=True, verbose_name='fecha fin'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='population_filter_api',
            field=models.CharField(max_length=2000, null=True, verbose_name='filtro poblacional API'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='role de acceso'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.service', verbose_name='servicio'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='start_date',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
    ]
