# Generated by Django 3.2.7 on 2021-10-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0031_auto_20211003_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='population_filter_api',
            field=models.CharField(max_length=2000, verbose_name='filtro poblacional API'),
        ),
    ]
