# Generated by Django 3.2.7 on 2021-10-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0032_alter_serviceconfiguration_population_filter_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='population_filter_api',
            field=models.CharField(max_length=2000, null=True, verbose_name='filtro poblacional API'),
        ),
    ]
