# Generated by Django 3.2.7 on 2021-10-04 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0033_alter_serviceconfiguration_population_filter_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='delivery_days',
            field=models.IntegerField(null=True, verbose_name='dias de entrega'),
        ),
        migrations.CreateModel(
            name='MainFormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(null=True, verbose_name='activo')),
                ('order_display', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero')], max_length=80, verbose_name='orden para mostrar')),
                ('main_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_section_form', to='request.mainsection', verbose_name='Sección principal formulario')),
                ('rule_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules_service_main_form_section', to='request.serviceconfiguration', verbose_name='Regla de servicio')),
            ],
            options={
                'verbose_name': 'seccion principal de formulario',
                'verbose_name_plural': 'secciones principales de formularios',
                'db_table': 'request_main_form_section',
            },
        ),
    ]
