# Generated by Django 3.2.7 on 2021-10-15 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0033_alter_subsectionserviceform_section_main_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsectionserviceform',
            name='section_main_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='request.mainformsection', to_field='main_section', verbose_name='grupo principal del formulario'),
        ),
    ]
