# Generated by Django 3.2.7 on 2021-10-04 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0034_auto_20211003_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainformsection',
            name='order_display',
            field=models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto')], max_length=80, verbose_name='orden para mostrar'),
        ),
        migrations.CreateModel(
            name='subsectionServiceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(null=True, verbose_name='activo')),
                ('order_display', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto')], max_length=80, verbose_name='orden para mostrar')),
                ('main_form_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_form', to='request.mainformsection', verbose_name='grupo principal del formulario')),
                ('rule_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules_service_main_form_subsection', to='request.serviceconfiguration', verbose_name='Regla de servicio')),
                ('subsection_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsection_form', to='request.subsection', verbose_name='subsección formulario')),
            ],
        ),
    ]
