# Generated by Django 3.2.7 on 2021-10-04 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0035_auto_20211003_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsectionserviceform',
            name='main_form_id',
        ),
        migrations.AddField(
            model_name='subsectionserviceform',
            name='section_main_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_form', to='request.mainsection', verbose_name='grupo principal del formulario'),
        ),
    ]
