# Generated by Django 3.2.7 on 2021-10-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0036_auto_20211003_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsectionserviceform',
            options={'verbose_name': 'componente y seccion form', 'verbose_name_plural': 'componentes y secciones form'},
        ),
        migrations.AlterModelTable(
            name='subsectionserviceform',
            table='request_section_component',
        ),
    ]
