# Generated by Django 3.2.7 on 2021-10-04 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0037_auto_20211003_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='etiqueta del componente')),
                ('required', models.BooleanField(null=True, verbose_name='requerido')),
                ('source_api', models.CharField(max_length=2000, null=True, verbose_name='fuente de datos API')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.componenttype', verbose_name='componente')),
                ('rule_subsetion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.subsectionserviceform', verbose_name='Subsección de servicio')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='request.datasource', verbose_name='fuente de datos')),
            ],
        ),
    ]
