# Generated by Django 3.2.7 on 2021-10-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0038_componentsubsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentsubsection',
            options={'verbose_name': 'componente y subsección', 'verbose_name_plural': 'componentes y subsecciones'},
        ),
        migrations.RenameField(
            model_name='componentsubsection',
            old_name='rule_subsetion',
            new_name='rule_subsection',
        ),
        migrations.AlterModelTable(
            name='componentsubsection',
            table='request_component_subsection',
        ),
    ]
