# Generated by Django 3.2.7 on 2021-10-15 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0039_auto_20211014_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentsubsection',
            name='component_action',
        ),
    ]
