# Generated by Django 3.2.7 on 2021-10-15 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0040_remove_componentsubsection_component_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsubsection',
            name='component_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='request.componentsubsection', verbose_name='componente de acción'),
        ),
    ]
