# Generated by Django 3.2.7 on 2021-10-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0041_componentsubsection_component_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentmainform',
            name='key_head',
            field=models.CharField(blank='', choices=[('COD', 'HEAD - Codigo del solicitante'), ('EMALS', 'HEAD - Email del Solicitante')], max_length=10, verbose_name='key head'),
        ),
        migrations.AlterField(
            model_name='componentsubsection',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.componenttype', verbose_name='tipo de componente'),
        ),
        migrations.AlterField(
            model_name='componentsubsection',
            name='key_head',
            field=models.CharField(blank=True, choices=[('COD', 'HEAD - Codigo del solicitante'), ('EMALS', 'HEAD - Email del Solicitante')], max_length=10, verbose_name='key head'),
        ),
    ]
