# Generated by Django 3.2.7 on 2021-10-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0041_componentsubsection_key_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentsubsection',
            name='key_head',
            field=models.CharField(blank='', default='', max_length=10, verbose_name='key head'),
        ),
    ]
