# Generated by Django 3.2.7 on 2021-10-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0042_alter_componentsubsection_key_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentsubsection',
            name='key_head',
        ),
    ]
