# Generated by Django 3.2.7 on 2021-10-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0043_remove_componentsubsection_key_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsubsection',
            name='key_head',
            field=models.CharField(blank='', default='0', max_length=10, verbose_name='key head'),
        ),
    ]
