# Generated by Django 3.2.7 on 2021-10-16 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0043_auto_20211015_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryservice',
            options={'verbose_name': 'categoria de servicio', 'verbose_name_plural': 'categoria de servicios'},
        ),
        migrations.AlterModelOptions(
            name='componenttype',
            options={'verbose_name': 'tipo de componente', 'verbose_name_plural': 'tipo de componentes'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'sede administrativa', 'verbose_name_plural': 'sedes administrativas'},
        ),
        migrations.AlterModelOptions(
            name='mainsection',
            options={'verbose_name': 'sección principal de fomulario', 'verbose_name_plural': 'sección principal de formularios'},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={'verbose_name': 'subsección de formulario', 'verbose_name_plural': 'subsección de formularios'},
        ),
        migrations.AlterField(
            model_name='categoryservice',
            name='description',
            field=models.CharField(max_length=100, unique=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='description',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre de componente'),
        ),
        migrations.AlterField(
            model_name='configvariable',
            name='code',
            field=models.CharField(max_length=10, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre entidad'),
        ),
        migrations.AlterField(
            model_name='footerweb',
            name='description',
            field=models.CharField(max_length=150, unique=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='mainsection',
            name='description',
            field=models.CharField(max_length=250, unique=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.categoryservice', verbose_name='categoría de servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.entity', verbose_name='sede administrativa'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='description',
            field=models.CharField(max_length=250, unique=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='key_config',
            field=models.ForeignKey(blank=True, limit_choices_to={'group_variable': ('HDSOL', 'BDSOL')}, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.configvariable', verbose_name='key config'),
        ),
        migrations.AlterUniqueTogether(
            name='footerweb',
            unique_together={('description', 'orientation', 'order_display')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('description', 'category_service', 'entity')},
        ),
    ]
