# Generated by Django 3.2.7 on 2021-10-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0044_componentsubsection_key_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentsubsection',
            name='key_head',
            field=models.CharField(blank='', choices=[('DNSC', 'HEAD-Direcciòn Nacional'), ('EMALS', 'HEAD-Correo del solicitante'), ('PROG', 'BODY-Programa académico')], max_length=10, verbose_name='key head'),
        ),
    ]
