# Generated by Django 3.2.7 on 2021-10-16 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0044_auto_20211015_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsection',
            old_name='key_config',
            new_name='key_config_id',
        ),
    ]
