# Generated by Django 3.2.7 on 2021-10-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0045_rename_key_config_subsection_key_config_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='key_config_id',
        ),
        migrations.AddField(
            model_name='subsection',
            name='key_config',
            field=models.CharField(blank=True, choices=[], max_length=10, null=True, verbose_name='key config'),
        ),
    ]
