# Generated by Django 3.2.7 on 2021-10-05 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0045_alter_componentsubsection_key_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentsubsection',
            name='key_head',
            field=models.CharField(blank='', choices=[('DNSC', 'HEAD - Direcciòn Nacional'), ('EMALS', 'HEAD - Correo del solicitante'), ('PROG', 'BODY - Programa académico')], max_length=10, verbose_name='key head'),
        ),
        migrations.CreateModel(
            name='ComponentMainForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='etiqueta del componente')),
                ('required', models.BooleanField(null=True, verbose_name='requerido')),
                ('source_api', models.CharField(max_length=2000, null=True, verbose_name='fuente de datos API')),
                ('key_head', models.CharField(blank='', choices=[('DNSC', 'HEAD - Direcciòn Nacional'), ('EMALS', 'HEAD - Correo del solicitante'), ('PROG', 'BODY - Programa académico')], max_length=10, verbose_name='key head')),
                ('order_display', models.IntegerField(null=True, verbose_name='orden despliegue')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.componenttype', verbose_name='componente')),
                ('rule_main_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.mainformsection', verbose_name='Subsección de servicio')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='request.datasource', verbose_name='fuente de datos')),
            ],
            options={
                'verbose_name': 'seccion principal y componente',
                'verbose_name_plural': 'secciones principales y componentes',
                'db_table': 'request_section_main_component',
            },
        ),
    ]
