# Generated by Django 3.2.7 on 2021-10-16 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0046_auto_20211015_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='key_config',
            field=models.ForeignKey(blank=True, limit_choices_to={'group_variable': ('HDSOL', 'BDSOL')}, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.configvariable', verbose_name='key config'),
        ),
    ]
