# Generated by Django 3.2.7 on 2021-10-05 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0046_auto_20211004_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainformsection',
            options={'verbose_name': 'seccion principal y componentes form', 'verbose_name_plural': 'secciones principales y componentes form'},
        ),
    ]
