# Generated by Django 3.2.7 on 2021-10-16 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0047_alter_subsection_key_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentmainform',
            name='key_head',
            field=models.CharField(blank='', choices=[], max_length=10, verbose_name='key head'),
        ),
        migrations.AlterField(
            model_name='componentsubsection',
            name='key_head',
            field=models.CharField(blank=True, choices=[], max_length=10, verbose_name='key head'),
        ),
        migrations.AlterField(
            model_name='datasourcevalue',
            name='data_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.datasourcevalue', verbose_name='dato de fuente relacionada'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='key_config',
            field=models.ForeignKey(blank=True, limit_choices_to={'group_variable': ('SECDF',)}, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.configvariable', verbose_name='key config'),
        ),
    ]
