# Generated by Django 3.2.7 on 2021-10-05 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0047_alter_mainformsection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainformsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainformsection',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de modicación'),
        ),
        migrations.AddField(
            model_name='mainformsection',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='modificado por'),
        ),
    ]
