# Generated by Django 3.2.7 on 2021-10-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0048_auto_20211004_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('estimated_time', models.TimeField(verbose_name='tiempo estimado de solución')),
            ],
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='working_hours',
            field=models.BooleanField(default=False, null=True, verbose_name='horas laborales'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='bussiness_days',
            field=models.BooleanField(default=False, null=True, verbose_name='dias laborales'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='delivery_days',
            field=models.IntegerField(default=False, null=True, verbose_name='dias de entrega'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='is_active',
            field=models.BooleanField(default=False, null=True, verbose_name='activo'),
        ),
    ]
