# Generated by Django 3.2.7 on 2021-10-16 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0049_auto_20211015_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainformsection',
            options={'verbose_name': 'seccion principal de formularios', 'verbose_name_plural': 'sección principal de formularios'},
        ),
        migrations.AlterModelOptions(
            name='subsectionserviceform',
            options={'verbose_name': 'subsección de sección principal de formulario', 'verbose_name_plural': 'subsección de sección principal de formularios'},
        ),
        migrations.RemoveField(
            model_name='componentsubsection',
            name='key_head',
        ),
        migrations.AddField(
            model_name='componentsubsection',
            name='key_config',
            field=models.ForeignKey(blank=True, limit_choices_to={'group_variable': ('HDSOL', 'BDSOL')}, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.configvariable', verbose_name='key config'),
        ),
        migrations.AlterField(
            model_name='serviceconfigurationstatus',
            name='status_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.status', verbose_name='estado de solicitud'),
        ),
        migrations.AlterField(
            model_name='subsectionserviceform',
            name='order_display',
            field=models.IntegerField(verbose_name='orden para mostrar'),
        ),
    ]
