# Generated by Django 3.2.7 on 2021-10-08 01:08

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0049_auto_20211007_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='estimated_time',
        ),
        migrations.AddField(
            model_name='priority',
            name='color_priority',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='Color de prioridad'),
        ),
        migrations.AddField(
            model_name='priority',
            name='priority_percentage',
            field=models.FloatField(default=0.0, verbose_name='porcentaje de prioridad'),
        ),
    ]
