# Generated by Django 3.2.7 on 2021-10-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0050_auto_20211016_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentmainform',
            name='component',
        ),
        migrations.RemoveField(
            model_name='componentmainform',
            name='rule_main_form',
        ),
        migrations.RemoveField(
            model_name='componentmainform',
            name='source',
        ),
        migrations.AlterModelOptions(
            name='requestheader',
            options={'verbose_name': 'gestión de la solicitud', 'verbose_name_plural': 'gestión de solicitudes'},
        ),
        migrations.AddField(
            model_name='requestheader',
            name='email_applicant',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo del solicitante'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='description',
            field=models.CharField(max_length=255, unique=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='priority_percentage',
            field=models.FloatField(default=0.0, unique=True, verbose_name='porcentaje de prioridad'),
        ),
        migrations.DeleteModel(
            name='ComponentAction',
        ),
        migrations.DeleteModel(
            name='ComponentMainForm',
        ),
    ]
