# Generated by Django 3.2.7 on 2021-10-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0051_auto_20211007_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='código de estado')),
                ('description', models.CharField(max_length=150, verbose_name='descripción')),
                ('completion_status', models.BooleanField(verbose_name='estado de terminación')),
                ('visible_state', models.BooleanField(verbose_name='estado visible')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
            ],
            options={
                'verbose_name': 'estado de solicitud',
                'verbose_name_plural': 'estados de solicitudes',
            },
        ),
    ]
