# Generated by Django 3.2.7 on 2021-10-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0052_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConfigurationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_start', models.BooleanField(verbose_name='Estado de inicio')),
                ('status_finished', models.BooleanField(verbose_name='estado de fin')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='modificado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modicación')),
                ('rule_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.serviceconfiguration', verbose_name='Servicio')),
                ('status_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.status', verbose_name='Estado de solicitud')),
            ],
            options={
                'verbose_name': 'estado relacionado a solicitud',
                'verbose_name_plural': 'estados relacionados a solicitudes',
                'db_table': 'request_status_related_request',
            },
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='related_status',
            field=models.ManyToManyField(through='request.ServiceConfigurationStatus', to='request.Status'),
        ),
    ]
