# Generated by Django 3.2.7 on 2021-10-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0054_serviceconfigurationstatus_assign_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfiguration',
            name='is_payment',
            field=models.BooleanField(default=False, null=True, verbose_name='Requiere pago'),
        ),
    ]
