# Generated by Django 3.2.7 on 2021-10-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0057_alter_serviceconfiguration_days_validity_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba_field', models.CharField(max_length=255)),
            ],
        ),
    ]
