# Generated by Django 3.2.7 on 2021-10-10 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0058_componentaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentaction',
            options={'verbose_name': 'componente de acción formularios', 'verbose_name_plural': 'componentes de acción formularios'},
        ),
        migrations.RemoveField(
            model_name='componentaction',
            name='prueba_field',
        ),
        migrations.AddField(
            model_name='componentaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 10, 16, 58, 34, 477666, tzinfo=utc), verbose_name='fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentaction',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de modicación'),
        ),
        migrations.AddField(
            model_name='componentaction',
            name='service_component_group_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='componentaction',
            name='service_component_section_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='componentaction',
            name='service_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='request.serviceconfiguration', verbose_name='Servicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentaction',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='modificado por'),
        ),
        migrations.AlterModelTable(
            name='componentaction',
            table='request_component_action',
        ),
    ]
