# Generated by Django 3.2.7 on 2021-10-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0060_auto_20211010_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentaction',
            name='service_component_group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='request.mainsection', verbose_name='grupo de componentes'),
        ),
    ]
