# Generated by Django 3.2.7 on 2021-10-10 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0061_alter_componentaction_service_component_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentaction',
            name='service_component_section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='request.subsection', verbose_name='seccion de formularios'),
        ),
    ]
